apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: expense
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        tier: database
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    project: expense
    tier: database
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port
